import fs from 'fs';

const poly = JSON.parse(fs.readFileSync('poly.json', 'utf8'));
// Build slug -> string[] of requirement items (split on ", ").
const map = {};
for (const p of poly) {
  const items = p.req
    .split(/,\s*/)
    .map((s) => s.trim())
    .filter(Boolean);
  if (items.length) map[p.slug] = items;
}
// Stable: sort keys alphabetically.
const sorted = Object.keys(map).sort();

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
let out = `// AUTO-GENERATED by scripts/gen-hab-req.mjs from Polygon's Pokopia habitat list.
// Source: https://www.polygon.com/pokemon-pokopia-habitat-dex-list-requirements-unlock/
// Keyed by habitat slug (habitatSlug(name) = lowercased, spaces -> hyphens).
// Each value lists the items/conditions needed to build that habitat.

export const HABITAT_REQUIREMENTS: Record<string, string[]> = {
`;
for (const slug of sorted) {
  const items = map[slug].map((i) => `'${esc(i)}'`).join(', ');
  out += `  '${esc(slug)}': [${items}],\n`;
}
out += `};\n`;

fs.writeFileSync('src/data/habitatRequirements.ts', out);
console.log('wrote', sorted.length, 'habitat requirement entries');
